/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all of your component files.
  content: ['./App.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      fontFamily: {
        // sans: ['Inter'],
        // inter: ['Inter'],
        // interThin: ['Inter-Thin'],
        // interExtraLight: ['Inter-ExtraLight'],
        // interLight: ['Inter-Light'],
        // interRegular: ['Inter-Regular'],
        // interMedium: ['Inter-Medium'],
        // interSemiBold: ['Inter-SemiBold'],
        // interBold: ['Inter-Bold'],
        // interExtraBold: ['Inter-ExtraBold'],
        sans: ['SF-Pro-Display-Regular', 'sans-serif'],
        DMSer: ['DMSerifDisplay'],
        DMSerRegular: ['DMSerifDisplay-Regular'],
        SF: ['SF-Pro-Display-Regular'],
      },
      colors: {
        primary: '#2F68FF',
        light: '#EAF0FF',
        lightGray: '#8C97AB',
        lightBlue: '#F0E9FD',
        borderColor: '#E0E3E8',
        blueBorder: '#C2A5F6',
        lightBorder: '#EAECF0',
        bgColor: '#F5F6F8',
        bgLight: '#ECEEF1',
        grayColor: '#5D6679',
        textColor: '#0F274F',
        blueColor: '#8348EE',
        iconColor: '#242424',
        sndTextColor: '#465977',
        otpBorderColor: '#465977',
        grayBorderColor: '#C3C9D3',
        deepGray: '#D9D9D9',
        deepPink: '#C0B9FD',
        active: '#6A23EA',
        pointColor: '#E0E3E8',
        error: '#FF4242',
        pink: '#61708B',
        // Custom gradient stops
        'primary-gradient-1': '#A97FF3',
        'primary-gradient-2': '#6A23EA',
      },
    },
  },
  plugins: [],
};
